import { ICON_QUESTIONMARK, UNKNOWN_CLASS, UNKNOWN_RACE, UNKNOWN_SPEC } from "$lib/consts";
import type { GameVersionType } from "$lib/versions/GameVersionTypes";

export const versionType: GameVersionType = {
    classes: [
        {
            name: "Warrior",
            icon: "classicon_warrior"
        },
        {
            name: "Rogue",
            icon: "classicon_rogue"
        },
        {
            name: "Paladin",
            icon: "classicon_paladin"
        },
        {
            name: "Mage",
            icon: "classicon_mage"
        },
        {
            name: "Priest",
            icon: "classicon_priest"
        },
        {
            name: "Warlock",
            icon: "classicon_warlock"
        },
        {
            name: "Druid",
            icon: "classicon_druid"
        },
        {
            name: "Shaman",
            icon: "classicon_shaman"
        },
        {
            name: "Hunter",
            icon: "classicon_hunter"
        },
        { name: UNKNOWN_CLASS, icon: ICON_QUESTIONMARK }
    ],
    specs: [
        { name: "DruidBalance", icon: "spell_nature_starfall", class: "Druid" },
        { name: "DruidFeral", icon: "ability_druid_catform", class: "Druid" },
        { name: "DruidGuardian", icon: "ability_racial_bearform", class: "Druid" },
        { name: "DruidRestoration", icon: "spell_nature_healingtouch", class: "Druid" },
        { name: "HunterBeastmastery", icon: "ability_hunter_bestialdiscipline", class: "Hunter" },
        { name: "HunterMarksmanship", icon: "ability_hunter_focusedaim", class: "Hunter" },
        { name: "HunterSurvival", icon: "ability_hunter_camouflage", class: "Hunter" },
        { name: "MageArcane", icon: "spell_holy_magicalsentry", class: "Mage" },
        { name: "MageFire", icon: "spell_fire_firebolt02", class: "Mage" },
        { name: "MageFrost", icon: "spell_frost_frostbolt02", class: "Mage" },
        { name: "PriestDiscipline", icon: "spell_holy_powerwordshield", class: "Priest" },
        { name: "PriestHoly", icon: "spell_holy_guardianspirit", class: "Priest" },
        { name: "PriestShadow", icon: "spell_shadow_shadowwordpain", class: "Priest" },
        { name: "PaladinHoly", icon: "spell_holy_holybolt", class: "Paladin" },
        { name: "PaladinProtection", icon: "ability_paladin_shieldofthetemplar", class: "Paladin" },
        { name: "PaladinRetribution", icon: "spell_holy_auraoflight", class: "Paladin" },
        { name: "RogueAssassination", icon: "ability_rogue_eviscerate", class: "Rogue" },
        { name: "RogueCombat", icon: "ability_backstab", class: "Rogue" },
        { name: "RogueSubtlety", icon: "ability_stealth", class: "Rogue" },
        { name: "WarlockAffliction", icon: "spell_shadow_deathcoil", class: "Warlock" },
        { name: "WarlockDemonology", icon: "spell_shadow_metamorphosis", class: "Warlock" },
        { name: "WarlockDestruction", icon: "spell_shadow_rainoffire", class: "Warlock" },
        { name: "ShamanElemental", icon: "spell_nature_lightning", class: "Shaman" },
        { name: "ShamanEnhancement", icon: "spell_shaman_improvedstormstrike", class: "Shaman" },
        { name: "ShamanRestoration", icon: "spell_nature_magicimmunity", class: "Shaman" },
        { name: "WarriorArms", icon: "ability_warrior_savageblow", class: "Warrior" },
        { name: "WarriorFury", icon: "ability_warrior_innerrage", class: "Warrior" },
        { name: "WarriorProtection", icon: "ability_warrior_defensivestance", class: "Warrior" },
        { name: UNKNOWN_SPEC, icon: ICON_QUESTIONMARK, class: UNKNOWN_CLASS }
    ],
    races: [
        {
            name: "Human",
            icon_male: "race_human_male",
            icon_female: "race_human_female",
        },
        {
            name: "Dwarf",
            icon_male: "race_dwarf_male",
            icon_female: "race_dwarf_female",
        },
        {
            name: "Gnome",
            icon_male: "race_gnome_male",
            icon_female: "race_gnome_female",
        },
        {
            name: "Nightelf",
            icon_male: "race_night-elf_male",
            icon_female: "race_night-elf_female",
        },
        {
            name: "Orc",
            icon_male: "race_orc_male",
            icon_female: "race_orc_female",
        },
        {
            name: "Troll",
            icon_male: "race_troll_male",
            icon_female: "race_troll_female",
        },
        {
            name: "Tauren",
            icon_male: "race_tauren_male",
            icon_female: "race_tauren_female",
        },
        {
            name: "Undead",
            icon_male: "race_undead_male",
            icon_female: "race_undead_female",
        },
        { name: UNKNOWN_RACE, icon_male: ICON_QUESTIONMARK, icon_female: ICON_QUESTIONMARK }
    ],
    raceClasses: [
        { "race": "Dwarf", "class": "Hunter" },
        { "race": "Dwarf", "class": "Paladin" },
        { "race": "Dwarf", "class": "Priest" },
        { "race": "Dwarf", "class": "Rogue" },
        { "race": "Dwarf", "class": "Warrior" },
        { "race": "Gnome", "class": "Mage" },
        { "race": "Gnome", "class": "Rogue" },
        { "race": "Gnome", "class": "Warlock" },
        { "race": "Gnome", "class": "Warrior" },
        { "race": "Human", "class": "Mage" },
        { "race": "Human", "class": "Paladin" },
        { "race": "Human", "class": "Priest" },
        { "race": "Human", "class": "Rogue" },
        { "race": "Human", "class": "Warlock" },
        { "race": "Human", "class": "Warrior" },
        { "race": "Nightelf", "class": "Druid" },
        { "race": "Nightelf", "class": "Hunter" },
        { "race": "Nightelf", "class": "Priest" },
        { "race": "Nightelf", "class": "Rogue" },
        { "race": "Nightelf", "class": "Warrior" },
        { "race": "Orc", "class": "Hunter" },
        { "race": "Orc", "class": "Rogue" },
        { "race": "Orc", "class": "Shaman" },
        { "race": "Orc", "class": "Warlock" },
        { "race": "Orc", "class": "Warrior" },
        { "race": "Tauren", "class": "Druid" },
        { "race": "Tauren", "class": "Hunter" },
        { "race": "Tauren", "class": "Shaman" },
        { "race": "Tauren", "class": "Warrior" },
        { "race": "Troll", "class": "Hunter" },
        { "race": "Troll", "class": "Mage" },
        { "race": "Troll", "class": "Priest" },
        { "race": "Troll", "class": "Rogue" },
        { "race": "Troll", "class": "Shaman" },
        { "race": "Troll", "class": "Warrior" },
        { "race": "Undead", "class": "Mage" },
        { "race": "Undead", "class": "Priest" },
        { "race": "Undead", "class": "Rogue" },
        { "race": "Undead", "class": "Warlock" },
        { "race": "Undead", "class": "Warrior" }],
    factionRaces: [
        {
            faction: "Horde",
            race: "Orc"
        }, {
            faction: "Horde",
            race: "Troll"
        }, {
            faction: "Horde",
            race: "Tauren"
        }, {
            faction: "Horde",
            race: "Undead"
        }, {
            faction: "Alliance",
            race: "Human"
        }, {
            faction: "Alliance",
            race: "Nightelf"
        }, {
            faction: "Alliance",
            race: "Dwarf"
        }, {
            faction: "Alliance",
            race: "Gnome"
        }],
    maxLevel: 60,
    talents: {
        druid: {
            15: null,
            30: null,
            45: null,
            60: null,
            75: null,
            90: null,
            talent_tree: {
                names: ["Balance", "Feral", "Restoration"],
                1: [
                    { name: "Test", icon: "ICON", cell: "0,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "0,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "5,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "6,1", connection: null, ranks: [] },
                ],
                2: [
                    { name: "Test", icon: "ICON", cell: "0,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "0,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "5,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "6,1", connection: null, ranks: [] },
                ],
                3: [
                    { name: "Test", icon: "ICON", cell: "0,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "0,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "5,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "6,1", connection: null, ranks: [] },
                ]
            }
        },
        deathknight: {
            15: null,
            30: null,
            45: null,
            60: null,
            75: null,
            90: null,
            talent_tree: {
                names: [],
                1: [],
                2: [],
                3: []
            }
        },
        rogue: {
            15: null,
            30: null,
            45: null,
            60: null,
            75: null,
            90: null,
            talent_tree: {
                names: ["Assassination", "Combat", "Subtlety"],
                1: [
                    { name: "Test", icon: "ICON", cell: "0,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "0,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "5,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "6,1", connection: null, ranks: [] },
                ],
                2: [
                    { name: "Test", icon: "ICON", cell: "0,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "0,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "5,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "6,1", connection: null, ranks: [] },
                ],
                3: [
                    { name: "Test", icon: "ICON", cell: "0,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "0,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "5,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "6,1", connection: null, ranks: [] },
                ]
            }
        },
        paladin: {
            15: null,
            30: null,
            45: null,
            60: null,
            75: null,
            90: null,
            talent_tree: {
                names: ["Holy", "Protection", "Retribution"],
                1: [
                    { name: "Test", icon: "ICON", cell: "0,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "0,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "5,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "6,1", connection: null, ranks: [] },
                ],
                2: [
                    { name: "Test", icon: "ICON", cell: "0,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "0,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "5,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "6,1", connection: null, ranks: [] },
                ],
                3: [
                    { name: "Test", icon: "ICON", cell: "0,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "0,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "5,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "6,1", connection: null, ranks: [] },
                ]
            }
        },
        priest: {
            15: null,
            30: null,
            45: null,
            60: null,
            75: null,
            90: null,
            talent_tree: {
                names: ["Discipline", "Holy", "Shadow"],
                1: [
                    { name: "Test", icon: "ICON", cell: "0,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "0,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "5,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "6,1", connection: null, ranks: [] },
                ],
                2: [
                    { name: "Test", icon: "ICON", cell: "0,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "0,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "5,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "6,1", connection: null, ranks: [] },
                ],
                3: [
                    { name: "Test", icon: "ICON", cell: "0,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "0,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "5,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "6,1", connection: null, ranks: [] },
                ]
            }
        },
        warlock: {
            15: null,
            30: null,
            45: null,
            60: null,
            75: null,
            90: null,
            talent_tree: {
                names: ["Affliction", "Demonology", "Destruction"],
                1: [
                    { name: "Test", icon: "ICON", cell: "0,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "0,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "5,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "6,1", connection: null, ranks: [] },
                ],
                2: [
                    { name: "Test", icon: "ICON", cell: "0,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "0,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "5,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "6,1", connection: null, ranks: [] },
                ],
                3: [
                    { name: "Test", icon: "ICON", cell: "0,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "0,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "5,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "6,1", connection: null, ranks: [] },
                ]
            }
        },
        warrior: {
            15: null,
            30: null,
            45: null,
            60: null,
            75: null,
            90: null,
            talent_tree: {
                names: ["Arms", "Fury", "Protection"],
                1: [
                    { name: "Test", icon: "ICON", cell: "0,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "0,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "5,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "6,1", connection: null, ranks: [] },
                ],
                2: [
                    { name: "Test", icon: "ICON", cell: "0,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "0,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "5,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "6,1", connection: null, ranks: [] },
                ],
                3: [
                    { name: "Test", icon: "ICON", cell: "0,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "0,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "5,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "6,1", connection: null, ranks: [] },
                ]
            }
        },
        shaman: {
            15: null,
            30: null,
            45: null,
            60: null,
            75: null,
            90: null,
            talent_tree: {
                names: ["Elemental", "Enhancement", "Restoration"],
                1: [
                    { name: "Test", icon: "ICON", cell: "0,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "0,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "5,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "6,1", connection: null, ranks: [] },
                ],
                2: [
                    { name: "Test", icon: "ICON", cell: "0,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "0,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "5,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "6,1", connection: null, ranks: [] },
                ],
                3: [
                    { name: "Test", icon: "ICON", cell: "0,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "0,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "1,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "2,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,0", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "3,3", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,1", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "4,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "5,2", connection: null, ranks: [] },
                    { name: "Test", icon: "ICON", cell: "6,1", connection: null, ranks: [] },
                ]
            }
        },
        hunter: {
            15: null,
            30: null,
            45: null,
            60: null,
            75: null,
            90: null,
            talent_tree: {
                names: ["Beastmastery", "Marksmanship", "Survival"],
                1: [
                    { name: "Improved Aspect of the Hawk", icon: "spell_nature_ravenform", cell: "0,1", connection: null, ranks: [19552,19553,19554,19555,19556] },
                    { name: "Endurance Training", icon: "spell_nature_reincarnation", cell: "0,2", connection: null, ranks: [19583,19584,19585,19586,19587] },
                    { name: "Improved Eyes of the Beast", icon: "ability_eyeoftheowl", cell: "1,0", connection: null, ranks: [19557,19558] },
                    { name: "Improved Aspect of the Monkey", icon: "ability_hunter_aspectofthemonkey", cell: "1,1", connection: null, ranks: [19549,19550,19551,24386,24387] },
                    { name: "Thick Hide", icon: "inv_misc_pelt_bear_03", cell: "1,2", connection: null, ranks: [19609,19610,19612] },
                    { name: "Improved Revive Pet", icon: "ability_hunter_beastsoothe", cell: "1,3", connection: null, ranks: [24443,19575] },
                    { name: "Pathfinding", icon: "ability_mount_jungletiger", cell: "2,0", connection: null, ranks: [19559,19560] },
                    { name: "Bestial Swiftness", icon: "ability_druid_dash", cell: "2,1", connection: null, ranks: [19596] },
                    { name: "Unleashed Fury", icon: "ability_bullrush", cell: "2,2", connection: null, ranks: [19616,19617,19618,19619,19620] },
                    { name: "Improved Mend Pet", icon: "ability_hunter_mendpet", cell: "3,1", connection: null, ranks: [19572,19573] },
                    { name: "Ferocity", icon: "inv_misc_monsterclaw_04", cell: "3,2", connection: "5,2", ranks: [19598,19599,19600,19601,19602] },
                    { name: "Spirit Bond", icon: "ability_druid_demoralizingroar", cell: "4,0", connection: null, ranks: [19578,20895] },
                    { name: "Intimidation", icon: "ability_devour", cell: "4,1", connection: "6,1", ranks: [19577] },
                    { name: "Bestial Discipline", icon: "spell_nature_abolishmagic", cell: "4,3", connection: null, ranks: [19590,19592] },
                    { name: "Frenzy", icon: "inv_misc_monsterclaw_03", cell: "5,2", connection: null, ranks: [19621,19622,19623,19624,19625] },
                    { name: "Bestial Wrath", icon: "ability_druid_ferociousbite", cell: "6,1", connection: null, ranks: [19574] },
                ],
                2: [
                    { name: "Improved Concussive Shot", icon: "spell_frost_stun", cell: "0,1", connection: null, ranks: [19407,19412,19413,19414,19415] },
                    { name: "Efficiency", icon: "spell_frost_wizardmark", cell: "0,2", connection: null, ranks: [19416,19417,19418,19419,19420] },
                    { name: "Improved Hunter's Mark", icon: "ability_hunter_snipershot", cell: "1,1", connection: null, ranks: [19421,19422,19423,19424,19425] },
                    { name: "Lethal Shots", icon: "ability_searingarrow", cell: "1,2", connection: "3,2", ranks: [19426,19427,19429,19430,19431] },
                    { name: "Aimed Shot", icon: "inv_spear_07", cell: "2,0", connection: null, ranks: [19434] },
                    { name: "Improved Arcane Shot", icon: "ability_impalingbolt", cell: "2,1", connection: null, ranks: [19454,19455,19456,19457,19458] },
                    { name: "Hawk Eye", icon: "ability_townwatch", cell: "2,3", connection: null, ranks: [19498,19499,19500] },
                    { name: "Improved Serpent Sting", icon: "ability_hunter_quickshot", cell: "3,1", connection: null, ranks: [19464,19465,19466,19467,19468] },
                    { name: "Mortal Shots", icon: "ability_piercedamage", cell: "3,2", connection: null, ranks: [19485,19487,19488,19489,19490] },
                    { name: "Scatter Shot", icon: "ability_golemstormbolt", cell: "4,0", connection: null, ranks: [19503] },
                    { name: "Barrage", icon: "ability_upgrademoonglaive", cell: "4,1", connection: "6,1", ranks: [19461,19462,24691] },
                    { name: "Improved Scorpid Sting", icon: "ability_hunter_criticalshot", cell: "4,2", connection: null, ranks: [19491,19493,19494] },
                    { name: "Ranged Weapon Specialization", icon: "inv_weapon_rifle_06", cell: "5,2", connection: null, ranks: [19507,19508,19509,19510,19511] },
                    { name: "Trueshot Aura", icon: "ability_trueshot", cell: "6,1", connection: null, ranks: [19506] },
                ],
                3: [
                    { name: "Monster Slaying", icon: "inv_misc_head_dragon_black", cell: "0,0", connection: null, ranks: [24293,24294,24295] },
                    { name: "Humanoid Slaying", icon: "spell_holy_prayerofhealing", cell: "0,1", connection: null, ranks: [19151,19152,19153] },
                    { name: "Deflection", icon: "ability_parry", cell: "0,2", connection: null, ranks: [19295,19297,19298,19301,19300] },
                    { name: "Entrapment", icon: "spell_nature_stranglevines", cell: "1,0", connection: null, ranks: [19184,19387,19388,19389,19390] },
                    { name: "Savage Strikes", icon: "ability_racial_bloodrage", cell: "1,1", connection: null, ranks: [19159,19160] },
                    { name: "Improved Wing Clip", icon: "ability_rogue_trip", cell: "1,2", connection: null, ranks: [19228,19232,19233,19234,19235] },
                    { name: "Clever Traps", icon: "spell_nature_timestop", cell: "2,0", connection: null, ranks: [19239,19245] },
                    { name: "Survivalist", icon: "spell_shadow_twilight", cell: "2,1", connection: null, ranks: [19255,19256,19257,19258,19259] },
                    { name: "Deterrence", icon: "ability_whirlwind", cell: "2,2", connection: "4,2", ranks: [19263] },
                    { name: "Trap Mastery", icon: "ability_ensnare", cell: "3,0", connection: null, ranks: [19376,19377] },
                    { name: "Surefooted", icon: "ability_kick", cell: "3,1", connection: null, ranks: [19290,19294,24283] },
                    { name: "Improved Feign Death", icon: "ability_rogue_feigndeath", cell: "3,3", connection: null, ranks: [19286,19287] },
                    { name: "Killer Instinct", icon: "spell_holy_blessingofstamina", cell: "4,1", connection: "6,1", ranks: [19370,19371,19373] },
                    { name: "Counterattack", icon: "ability_warrior_challange", cell: "4,2", connection: null, ranks: [19306] },
                    { name: "Lightning Reflexes", icon: "spell_nature_invisibilty", cell: "5,2", connection: null, ranks: [19168,19180,19181,24296,24297] },
                    { name: "Wyvern Sting", icon: "inv_spear_02", cell: "6,1", connection: null, ranks: [19386] },
                ]
            }
        },
        mage: {
            15: null,
            30: null,
            45: null,
            60: null,
            75: null,
            90: null,
            talent_tree: {
                names: ["Arcane", "Fire", "Frost"],
                1: [
                    { name: "Arcane Subtlety", icon: "spell_holy_dispelmagic", cell: "0,0", connection: null, ranks: [11210, 12592] },
                    { name: "Arcane Focus", icon: "spell_holy_devotion", cell: "0,1", connection: null, ranks: [11222, 12839, 12840, 12841, 12842] },
                    { name: "Improved Arcane Missiles", icon: "spell_nature_starfall", cell: "0,2", connection: null, ranks: [11237, 12463, 12464, 16769, 16770] },
                    { name: "Wand Specialization", icon: "inv_wand_01", cell: "1,0", connection: null, ranks: [6057, 6085] },
                    { name: "Magic Absorption", icon: "spell_nature_astralrecalgroup", cell: "1,1", connection: null, ranks: [29441, 29444, 29445, 29446, 29447] },
                    { name: "Arcane Concentration", icon: "spell_shadow_manaburn", cell: "1,2", connection: null, ranks: [11213, 12574, 12575, 12576, 12577] },
                    { name: "Magic Attunement", icon: "spell_nature_abolishmagic", cell: "2,0", connection: null, ranks: [11247, 12606] },
                    { name: "Improved Arcane Explosion", icon: "spell_nature_wispsplode", cell: "2,1", connection: null, ranks: [11242, 12467, 12469] },
                    { name: "Arcane Resilience", icon: "spell_arcane_arcaneresilience", cell: "2,2", connection: "4,2", ranks: [28574] },
                    { name: "Improved Mana Shield", icon: "spell_shadow_detectlesserinvisibility", cell: "3,0", connection: null, ranks: [11252, 12605] },
                    { name: "Improved Counterspell", icon: "spell_frost_iceshock", cell: "3,1", connection: null, ranks: [11255, 12598] },
                    { name: "Arcane Meditation", icon: "spell_shadow_siphonmana", cell: "3,3", connection: null, ranks: [18462, 18463, 18464] },
                    { name: "Presence of Mind", icon: "spell_nature_enchantarmor", cell: "4,1", connection: "5,1", ranks: [12043] },
                    { name: "Arcane Mind", icon: "spell_shadow_charm", cell: "4,2", connection: null, ranks: [11232, 12500, 12501, 12502, 12503] },
                    { name: "Arcane Instability", icon: "spell_shadow_teleport", cell: "5,1", connection: "6,1", ranks: [15058, 15059, 15060] },
                    { name: "Arcane Power", icon: "spell_nature_lightning", cell: "6,1", connection: null, ranks: [12042] },
                ],
                2: [
                    { name: "Improved Fireball", icon: "spell_fire_flamebolt", cell: "0,1", connection: null, ranks: [11069, 12338, 12339, 12340, 12341] },
                    { name: "Impact", icon: "spell_fire_meteorstorm", cell: "0,2", connection: null, ranks: [11103, 12357, 12358, 12359, 12360] },
                    { name: "Ignite", icon: "spell_fire_incinerate", cell: "1,0", connection: null, ranks: [11119, 11120, 12846, 12847, 12848] },
                    { name: "Flame Throwing", icon: "spell_fire_flare", cell: "1,1", connection: null, ranks: [11100, 12353] },
                    { name: "Improved Fire Blast", icon: "spell_fire_fireball", cell: "1,2", connection: null, ranks: [18459, 11080, 12342] },
                    { name: "Incinerate", icon: "spell_fire_flameshock", cell: "2,0", connection: null, ranks: [11213, 18460] },
                    { name: "Improved Flamestrike", icon: "spell_fire_selfdestruct", cell: "2,1", connection: null, ranks: [11108, 12349, 12350] },
                    { name: "Pyroblast", icon: "spell_fire_fireball02", cell: "2,2", connection: "4,2", ranks: [11366] },
                    { name: "Burning Soul", icon: "spell_fire_fire", cell: "2,3", connection: null, ranks: [11083, 12351] },
                    { name: "Improved Scorch", icon: "spell_fire_soulburn", cell: "3,0", connection: null, ranks: [11095, 12872, 12873] },
                    { name: "Improved Fire Ward", icon: "spell_fire_firearmor", cell: "3,1", connection: null, ranks: [11094, 13043] },
                    { name: "Master of Elements", icon: "spell_fire_masterofelements", cell: "3,3", connection: null, ranks: [29074, 29075, 29076] },
                    { name: "Critical Mass", icon: "spell_nature_wispheal", cell: "4,1", connection: "6,1", ranks: [11115, 11367, 11368] },
                    { name: "Blast Wave", icon: "spell_holy_excorcism_02", cell: "4,2", connection: null, ranks: [11113] },
                    { name: "Fire Power", icon: "spell_fire_immolation", cell: "5,2", connection: null, ranks: [11124, 12378, 12398, 12399, 12400] },
                    { name: "Combustion", icon: "spell_fire_sealoffire", cell: "6,1", connection: null, ranks: [11129] },
                ],
                3: [
                    { name: "Frost Warding", icon: "spell_frost_frostward", cell: "0,0", connection: null, ranks: [11189,28332] },
                    { name: "Improved Frostbolt", icon: "spell_frost_frostbolt02", cell: "0,1", connection: null, ranks: [11070,12473,16763,16765,16766] },
                    { name: "Elemental Precision", icon: "spell_ice_magicdamage", cell: "0,2", connection: null, ranks: [29438,29439,29440] },
                    { name: "Ice Shards", icon: "spell_frost_iceshard", cell: "1,0", connection: null, ranks: [11207,12672,15047,15052,15053] },
                    { name: "Frostbite", icon: "spell_frost_frostarmor", cell: "1,1", connection: null, ranks: [11071,12496,12497] },
                    { name: "Improved Frost Nova", icon: "spell_frost_freezingbreath", cell: "1,2", connection: "3,2", ranks: [11165,12475] },
                    { name: "Permafrost", icon: "spell_frost_wisp", cell: "1,3", connection: null, ranks: [11175,12569,12571] },
                    { name: "Piercing Ice", icon: "spell_frost_frostbolt", cell: "2,0", connection: null, ranks: [11151,12952,12953] },
                    { name: "Cold Snap", icon: "spell_frost_wizardmark", cell: "2,1", connection: null, ranks: [12472] },
                    { name: "Improved Blizzard", icon: "spell_frost_icestorm", cell: "2,3", connection: null, ranks: [11185,12487,12488] },
                    { name: "Arctic Reach", icon: "spell_shadow_darkritual", cell: "3,0", connection: null, ranks: [16757,16758] },
                    { name: "Frost Channeling", icon: "spell_frost_stun", cell: "3,1", connection: null, ranks: [11160,12518,12519] },
                    { name: "Shatter", icon: "spell_frost_frostshock", cell: "3,2", connection: null, ranks: [11170,12982,12983,12984,12985] },
                    { name: "Ice Block", icon: "spell_frost_frost", cell: "4,1", connection: "6,1", ranks: [11958] },
                    { name: "Improved Cone of Cold", icon: "spell_frost_glacier", cell: "4,2", connection: null, ranks: [11190,12489,12490] },
                    { name: "Winter's Chill", icon: "spell_frost_chillingblast", cell: "5,2", connection: null, ranks: [11180,28592,28593,28594,28595] },
                    { name: "Ice Barrier", icon: "spell_ice_lament", cell: "6,1", connection: null, ranks: [11426] },
                ]
            }
        },
        monk: {
            15: null,
            30: null,
            45: null,
            60: null,
            75: null,
            90: null,
            talent_tree: {
                names: [],
                1: [
                ],
                2: [
                ],
                3: [
                ]
            }
        }
    }
};